# SPDX-FileCopyrightText: 2026 Machine Builder AG
#
# SPDX-License-Identifier: MIT
#
# Starts the dummy-asset-link Asset Link for Industrial Asset Hub (IAH)
# Depends on an IAH gateway

services:
  dummy-asset-link:
    restart: always
    image: 'dummy-asset-link:latest-${AL_OS}-${AL_ARCH}'
    networks:
      - 01-cdm
    command:
      - '-grpc-server-endpoint-address=dummy-asset-link'
      - '-grpc-server-address=:8081'
      - '-grpc-registry-address=grpc-server-registry:50051'
    ports:
      - 8081:8081

networks:
  01-cdm:
    name: cdm
    external: true
